spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_one
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=Lt*08161554409
server.port=3030
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always