name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker hub
    - uses: docker/login-action@v2
      with:
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
    - run: docker build -t jumongweb/cloud_one:latest .

    - name: Push Docker image to Docker Hub
      run: docker push jumongweb/cloud_one:latest
