name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build and Push Docker Image
    - uses: Atticuszz/docker-image-build-push@v0.0.1
      with:
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        image_name: "jumongweb/lab_one_image:latest"